"""create code table

Revision ID: 2bf1ebd53382
Revises: 
Create Date: 2026-01-14 15:25:32.746762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf1ebd53382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('fingering', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codes_code'), 'codes', ['code'], unique=False)
    op.create_index(op.f('ix_codes_fingering'), 'codes', ['fingering'], unique=False)
    op.create_index(op.f('ix_codes_id'), 'codes', ['id'], unique=False)
    op.create_index(op.f('ix_codes_position'), 'codes', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codes_position'), table_name='codes')
    op.drop_index(op.f('ix_codes_id'), table_name='codes')
    op.drop_index(op.f('ix_codes_fingering'), table_name='codes')
    op.drop_index(op.f('ix_codes_code'), table_name='codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
