"""create todo table

Revision ID: bd7f71afc9d2
Revises: 
Create Date: 2026-01-14 22:22:53.113024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7f71afc9d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chord', sa.String(), nullable=True),
    sa.Column('fingering', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chords_chord'), 'chords', ['chord'], unique=False)
    op.create_index(op.f('ix_chords_fingering'), 'chords', ['fingering'], unique=False)
    op.create_index(op.f('ix_chords_id'), 'chords', ['id'], unique=False)
    op.create_index(op.f('ix_chords_position'), 'chords', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chords_position'), table_name='chords')
    op.drop_index(op.f('ix_chords_id'), table_name='chords')
    op.drop_index(op.f('ix_chords_fingering'), table_name='chords')
    op.drop_index(op.f('ix_chords_chord'), table_name='chords')
    op.drop_table('chords')
    # ### end Alembic commands ###
